// ---------- Core cart engine (used on every page) ----------

function getCart() {
  return JSON.parse(localStorage.getItem("cart")) || [];
}

function saveCart(cart) {
  localStorage.setItem("cart", JSON.stringify(cart));
}

function addToCart(id, qty = 1) {
  const product = products.find(p => p.id === id);
  if (!product || product.stock === 0) return;

  const cart = getCart();
  const existing = cart.find(item => item.id === id);

  if (existing) {
    existing.qty = Math.min(existing.qty + qty, product.stock);
  } else {
    cart.push({ id: id, qty: Math.min(qty, product.stock) });
  }

  saveCart(cart);
  updateCartBadge();
  showToast("Added to cart");
  if (document.getElementById("cart-items")) renderCartPage();
}

function removeFromCart(id) {
  let cart = getCart();
  cart = cart.filter(item => item.id !== id);
  saveCart(cart);
  updateCartBadge();
  if (document.getElementById("cart-items")) renderCartPage();
}

function updateCartQty(id, newQty) {
  const product = products.find(p => p.id === id);
  const cart = getCart();
  const item = cart.find(i => i.id === id);
  if (!item || !product) return;
  item.qty = Math.max(1, Math.min(newQty, product.stock));
  saveCart(cart);
  updateCartBadge();
  if (document.getElementById("cart-items")) renderCartPage();
}

function clearCart() {
  saveCart([]);
  updateCartBadge();
  if (document.getElementById("cart-items")) renderCartPage();
}

function updateCartBadge() {
  const badge = document.getElementById("cart-count");
  if (!badge) return;
  const totalQty = getCart().reduce((sum, item) => sum + item.qty, 0);
  badge.textContent = totalQty;
}

function calculateTotals(cart) {
  const subtotal = cart.reduce((sum, item) => {
    const p = products.find(pr => pr.id === item.id);
    return sum + (p ? p.salePrice * item.qty : 0);
  }, 0);
  const shipping = subtotal === 0 ? 0 : (subtotal > 5000 ? 0 : 100);
  const tax = Math.round(subtotal * 0.05);
  const total = subtotal + shipping + tax;
  return { subtotal, shipping, tax, total };
}

function money(n) {
  return "₹" + n.toLocaleString("en-IN");
}

function showToast(message) {
  let toast = document.getElementById("toast");
  if (!toast) {
    toast = document.createElement("div");
    toast.id = "toast";
    document.body.appendChild(toast);
  }
  toast.textContent = message;
  toast.classList.add("show");
  clearTimeout(window._toastTimer);
  window._toastTimer = setTimeout(() => toast.classList.remove("show"), 2000);
}

updateCartBadge();

// Add to Cart buttons anywhere on the site (event delegation, since product
// cards are generated by JavaScript and don't exist when the page first loads)
document.addEventListener("click", (e) => {
  const btn = e.target.closest(".add-btn");
  if (!btn || btn.disabled) return;
  addToCart(Number(btn.dataset.id), 1);
});

// ---------- Cart page rendering (only runs on cart.html) ----------

function cartRow(item) {
  const p = products.find(pr => pr.id === item.id);
  if (!p) return "";
  const subtotal = p.salePrice * item.qty;
  return `
    <div class="cart-row" data-id="${p.id}">
      <img src="${p.image}" alt="${p.name}">
      <div class="cart-row-info">
        <a href="product.html?id=${p.id}" class="card-name">${p.name}</a>
        <p class="cart-row-price">${money(p.salePrice)} each</p>
      </div>
      <div class="qty-selector small">
        <button class="cart-qty-minus" data-id="${p.id}">-</button>
        <span>${item.qty}</span>
        <button class="cart-qty-plus" data-id="${p.id}">+</button>
      </div>
      <p class="cart-row-subtotal">${money(subtotal)}</p>
      <button class="remove-btn" data-id="${p.id}" aria-label="Remove item">✕</button>
    </div>
  `;
}

function renderCartPage() {
  const cart = getCart();
  const itemsEl = document.getElementById("cart-items");
  const emptyEl = document.getElementById("cart-empty");
  const summaryEl = document.getElementById("cart-summary");

  if (cart.length === 0) {
    itemsEl.innerHTML = "";
    emptyEl.style.display = "block";
    summaryEl.style.display = "none";
    return;
  }

  emptyEl.style.display = "none";
  summaryEl.style.display = "block";
  itemsEl.innerHTML = cart.map(cartRow).join("");

  const { subtotal, shipping, tax, total } = calculateTotals(cart);
  document.getElementById("sum-subtotal").textContent = money(subtotal);
  document.getElementById("sum-shipping").textContent = shipping === 0 ? "FREE" : money(shipping);
  document.getElementById("sum-tax").textContent = money(tax);
  document.getElementById("sum-total").textContent = money(total);
}

if (document.getElementById("cart-items")) {
  renderCartPage();

  document.getElementById("cart-items").addEventListener("click", (e) => {
    const plus = e.target.closest(".cart-qty-plus");
    const minus = e.target.closest(".cart-qty-minus");
    const remove = e.target.closest(".remove-btn");

    if (plus) {
      const id = Number(plus.dataset.id);
      const item = getCart().find(i => i.id === id);
      updateCartQty(id, item.qty + 1);
    }
    if (minus) {
      const id = Number(minus.dataset.id);
      const item = getCart().find(i => i.id === id);
      updateCartQty(id, item.qty - 1);
    }
    if (remove) {
      removeFromCart(Number(remove.dataset.id));
      showToast("Item removed");
    }
  });

  const clearBtn = document.getElementById("clear-cart-btn");
  if (clearBtn) {
    clearBtn.addEventListener("click", () => {
      if (confirm("Remove all items from your cart?")) {
        clearCart();
        showToast("Cart cleared");
      }
    });
  }
}
